# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kvetinka/Documents/coalescence

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kvetinka/Documents/coalescence

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kvetinka/Documents/coalescence/CMakeFiles /home/kvetinka/Documents/coalescence/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kvetinka/Documents/coalescence/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named coalesce

# Build rule for target.
coalesce: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coalesce
.PHONY : coalesce

# fast build rule for target.
coalesce/fast:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/build
.PHONY : coalesce/fast

src/constants.o: src/constants.f90.o

.PHONY : src/constants.o

# target to build an object file
src/constants.f90.o:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/constants.f90.o
.PHONY : src/constants.f90.o

src/constants.i: src/constants.f90.i

.PHONY : src/constants.i

# target to preprocess a source file
src/constants.f90.i:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/constants.f90.i
.PHONY : src/constants.f90.i

src/constants.s: src/constants.f90.s

.PHONY : src/constants.s

# target to generate assembly for a file
src/constants.f90.s:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/constants.f90.s
.PHONY : src/constants.f90.s

src/globals.o: src/globals.f90.o

.PHONY : src/globals.o

# target to build an object file
src/globals.f90.o:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/globals.f90.o
.PHONY : src/globals.f90.o

src/globals.i: src/globals.f90.i

.PHONY : src/globals.i

# target to preprocess a source file
src/globals.f90.i:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/globals.f90.i
.PHONY : src/globals.f90.i

src/globals.s: src/globals.f90.s

.PHONY : src/globals.s

# target to generate assembly for a file
src/globals.f90.s:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/globals.f90.s
.PHONY : src/globals.f90.s

src/in_out.o: src/in_out.f90.o

.PHONY : src/in_out.o

# target to build an object file
src/in_out.f90.o:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/in_out.f90.o
.PHONY : src/in_out.f90.o

src/in_out.i: src/in_out.f90.i

.PHONY : src/in_out.i

# target to preprocess a source file
src/in_out.f90.i:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/in_out.f90.i
.PHONY : src/in_out.f90.i

src/in_out.s: src/in_out.f90.s

.PHONY : src/in_out.s

# target to generate assembly for a file
src/in_out.f90.s:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/in_out.f90.s
.PHONY : src/in_out.f90.s

src/integration.o: src/integration.f90.o

.PHONY : src/integration.o

# target to build an object file
src/integration.f90.o:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/integration.f90.o
.PHONY : src/integration.f90.o

src/integration.i: src/integration.f90.i

.PHONY : src/integration.i

# target to preprocess a source file
src/integration.f90.i:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/integration.f90.i
.PHONY : src/integration.f90.i

src/integration.s: src/integration.f90.s

.PHONY : src/integration.s

# target to generate assembly for a file
src/integration.f90.s:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/integration.f90.s
.PHONY : src/integration.f90.s

src/ioutils.o: src/ioutils.f90.o

.PHONY : src/ioutils.o

# target to build an object file
src/ioutils.f90.o:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/ioutils.f90.o
.PHONY : src/ioutils.f90.o

src/ioutils.i: src/ioutils.f90.i

.PHONY : src/ioutils.i

# target to preprocess a source file
src/ioutils.f90.i:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/ioutils.f90.i
.PHONY : src/ioutils.f90.i

src/ioutils.s: src/ioutils.f90.s

.PHONY : src/ioutils.s

# target to generate assembly for a file
src/ioutils.f90.s:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/ioutils.f90.s
.PHONY : src/ioutils.f90.s

src/list.o: src/list.f90.o

.PHONY : src/list.o

# target to build an object file
src/list.f90.o:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/list.f90.o
.PHONY : src/list.f90.o

src/list.i: src/list.f90.i

.PHONY : src/list.i

# target to preprocess a source file
src/list.f90.i:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/list.f90.i
.PHONY : src/list.f90.i

src/list.s: src/list.f90.s

.PHONY : src/list.s

# target to generate assembly for a file
src/list.f90.s:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/list.f90.s
.PHONY : src/list.f90.s

src/main.o: src/main.f90.o

.PHONY : src/main.o

# target to build an object file
src/main.f90.o:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/main.f90.o
.PHONY : src/main.f90.o

src/main.i: src/main.f90.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.f90.i:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/main.f90.i
.PHONY : src/main.f90.i

src/main.s: src/main.f90.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.f90.s:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/main.f90.s
.PHONY : src/main.f90.s

src/model.o: src/model.f90.o

.PHONY : src/model.o

# target to build an object file
src/model.f90.o:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/model.f90.o
.PHONY : src/model.f90.o

src/model.i: src/model.f90.i

.PHONY : src/model.i

# target to preprocess a source file
src/model.f90.i:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/model.f90.i
.PHONY : src/model.f90.i

src/model.s: src/model.f90.s

.PHONY : src/model.s

# target to generate assembly for a file
src/model.f90.s:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/model.f90.s
.PHONY : src/model.f90.s

src/opkda1.o: src/opkda1.f.o

.PHONY : src/opkda1.o

# target to build an object file
src/opkda1.f.o:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/opkda1.f.o
.PHONY : src/opkda1.f.o

src/opkda1.i: src/opkda1.f.i

.PHONY : src/opkda1.i

# target to preprocess a source file
src/opkda1.f.i:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/opkda1.f.i
.PHONY : src/opkda1.f.i

src/opkda1.s: src/opkda1.f.s

.PHONY : src/opkda1.s

# target to generate assembly for a file
src/opkda1.f.s:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/opkda1.f.s
.PHONY : src/opkda1.f.s

src/opkda2.o: src/opkda2.f.o

.PHONY : src/opkda2.o

# target to build an object file
src/opkda2.f.o:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/opkda2.f.o
.PHONY : src/opkda2.f.o

src/opkda2.i: src/opkda2.f.i

.PHONY : src/opkda2.i

# target to preprocess a source file
src/opkda2.f.i:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/opkda2.f.i
.PHONY : src/opkda2.f.i

src/opkda2.s: src/opkda2.f.s

.PHONY : src/opkda2.s

# target to generate assembly for a file
src/opkda2.f.s:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/opkda2.f.s
.PHONY : src/opkda2.f.s

src/opkdmain.o: src/opkdmain.f.o

.PHONY : src/opkdmain.o

# target to build an object file
src/opkdmain.f.o:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/opkdmain.f.o
.PHONY : src/opkdmain.f.o

src/opkdmain.i: src/opkdmain.f.i

.PHONY : src/opkdmain.i

# target to preprocess a source file
src/opkdmain.f.i:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/opkdmain.f.i
.PHONY : src/opkdmain.f.i

src/opkdmain.s: src/opkdmain.f.s

.PHONY : src/opkdmain.s

# target to generate assembly for a file
src/opkdmain.f.s:
	$(MAKE) -f CMakeFiles/coalesce.dir/build.make CMakeFiles/coalesce.dir/src/opkdmain.f.s
.PHONY : src/opkdmain.f.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... coalesce"
	@echo "... src/constants.o"
	@echo "... src/constants.i"
	@echo "... src/constants.s"
	@echo "... src/globals.o"
	@echo "... src/globals.i"
	@echo "... src/globals.s"
	@echo "... src/in_out.o"
	@echo "... src/in_out.i"
	@echo "... src/in_out.s"
	@echo "... src/integration.o"
	@echo "... src/integration.i"
	@echo "... src/integration.s"
	@echo "... src/ioutils.o"
	@echo "... src/ioutils.i"
	@echo "... src/ioutils.s"
	@echo "... src/list.o"
	@echo "... src/list.i"
	@echo "... src/list.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/model.o"
	@echo "... src/model.i"
	@echo "... src/model.s"
	@echo "... src/opkda1.o"
	@echo "... src/opkda1.i"
	@echo "... src/opkda1.s"
	@echo "... src/opkda2.o"
	@echo "... src/opkda2.i"
	@echo "... src/opkda2.s"
	@echo "... src/opkdmain.o"
	@echo "... src/opkdmain.i"
	@echo "... src/opkdmain.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

